import type { Metadata } from "next";
import localFont from "next/font/local";
import './reset.css'
import './globals.css'


const kantumruyPro = localFont({
  src: './Kantumruy/universal.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kantumruyPro.className}`}>
        {children}
      </body>
    </html>
  );
}
